"""add relations

Revision ID: 6309d39c0066
Revises: 8860532b990e
Create Date: 2023-08-24 11:44:50.207818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6309d39c0066'
down_revision: Union[str, None] = '8860532b990e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('engineer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'project', 'engineer', ['engineer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_column('project', 'engineer_id')
    # ### end Alembic commands ###
