"""add variables to project table

Revision ID: a942d27ce2ec
Revises: ed5914680965
Create Date: 2023-08-19 22:53:59.714348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a942d27ce2ec'
down_revision: Union[str, None] = 'ed5914680965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('title', sa.String(length=50), nullable=True))
    op.add_column('project', sa.Column('description', sa.String(length=150), nullable=True))
    op.add_column('project', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('project', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('project', sa.Column('urgency', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'urgency')
    op.drop_column('project', 'due_date')
    op.drop_column('project', 'start_date')
    op.drop_column('project', 'description')
    op.drop_column('project', 'title')
    # ### end Alembic commands ###
